#!/usr/bin/env python3


def checkout_func():
    from csProjectManager.projectManager import csGetRepository

    repo_cs_url = "git@github.com"
    branch = "cs-main"

    csGetRepository(
        repo_cs_url,
        "cscosine/csCMake.git",
        "csCMake",
        branch,
        needCMakeUserPathFile=False,
    )

    _ = csGetRepository
    pass


def build_func():
    from csProjectManager.projectManager import csWorkflow

    # for interface only libraries, generate a single configuration only (use release)
    # note, use the {} to enable properly the -po option (preset only)
    presetRelease = {
        "linux": ["linux-ninja{release}", "linux-ninja-multi-config-clang"],
        "windows": ["msvc2022-x64", "msvc2022-x64-LLVM"],
    }

    # use {debug|release}
    presetDebugRelease = {
        "linux": ["linux-ninja{debug|release}", "linux-ninja-multi-config-clang"],
        "windows": ["msvc2022-x64", "msvc2022-x64-LLVM"],
    }

    # use {debug|release|relWithDebInfo|paranoid}
    presetsAll = {
        "linux": [
            "linux-ninja{debug|release|relWithDebInfo|paranoid}",
            "linux-ninja-multi-config-clang",
        ],
        "windows": ["msvc2022-x64", "msvc2022-x64-LLVM"],
    }

    _ = presetRelease
    _ = presetDebugRelease
    _ = presetsAll

    _ = csWorkflow


############################################################################################
## -- BEGIN AUTOGENERATED CODE - DO NOT EDIT BELOW THIS POINT - IT WILL BE OVERWRITTEN -- ##


def main():
    import os
    import sys

    # Ensure script runs from its own directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    current_dir = os.getcwd()

    if current_dir != script_dir:
        print(
            f"Warning: The current directory ({current_dir}) is not the same as the script's directory ({script_dir}), changing to {script_dir}"
        )
        os.chdir(script_dir)

    # Check if GitPython is installed
    try:
        from git import Repo, GitCommandError
    except ImportError:
        print(
            "GitPython is not installed. Please install it using, for example, pip install GitPython --user",
            file=sys.stderr,
        )
        sys.exit(1)

    # get the repository to setup the project,
    csProjectManager_dir = "csProjectManager"
    csProjectManager_base_url = "git@github.com"
    csProjectManager_repo = "cscosine/csProjectManager.git"
    csProjectManager_branch = "cs-main"

    # if it does not exists, clone it
    if not os.path.isdir(csProjectManager_dir):
        try:
            print(
                f"Cloning the repository {csProjectManager_base_url}:{csProjectManager_repo} on branch {csProjectManager_branch} to {csProjectManager_dir}..."
            )
            Repo.clone_from(
                csProjectManager_base_url + ":" + csProjectManager_repo,
                csProjectManager_dir,
                branch=csProjectManager_branch,
            )
            print("... done")
        except GitCommandError as e:
            print(f"-- Git operation failed: {e}", file=sys.stderr)
            sys.exit(1)

    # Add csProjectManager directory to sys.path to allow module imports
    sys.path.insert(0, os.path.abspath(csProjectManager_dir))
    try:
        from csProjectManager.projectManager import csSetupProject, RepoCheckoutCommands

        print("Successfully imported csProjectManager module.")
        csSetupProject(
            csProjectManager=RepoCheckoutCommands(
                directory=csProjectManager_dir,
                base_url=csProjectManager_base_url,
                repo=csProjectManager_repo,
                branch=csProjectManager_branch,
                needCMakeUserPathFile=False,
            ),
            checkout_func=checkout_func,
            build_func=build_func,
        )
    except ImportError as e:
        print(f"Failed to import csProjectManager: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()

## --  END AUTOGENERATED CODE - DO NOT EDIT ABOVE THIS POINT - IT WILL BE OVERWRITTEN --  ##
############################################################################################
