name: 3rdPartyBaseLibs

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  csOrchestratorJob:
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            os_version: ubuntu22.04
            architecture: x64
            architecture_variant: generic
            compiler: gcc
            compiler_version: default
            generator: ninja
            generator_type: singleconfig
            runner: ubuntu-22.04
          - os: linux
            os_version: ubuntu22.04
            architecture: x64
            architecture_variant: generic
            compiler: gcc
            compiler_version: default
            generator: ninjamulticonfig
            generator_type: multiconfig
            runner: ubuntu-22.04
          - os: linux
            os_version: ubuntu22.04
            architecture: x64
            architecture_variant: generic
            compiler: clang
            compiler_version: default
            generator: ninja
            generator_type: singleconfig
            runner: ubuntu-22.04
          - os: linux
            os_version: ubuntu22.04
            architecture: x64
            architecture_variant: generic
            compiler: clang
            compiler_version: default
            generator: ninjamulticonfig
            generator_type: multiconfig
            runner: ubuntu-22.04
          - os: linux
            os_version: ubuntu24.04
            architecture: x64
            architecture_variant: generic
            compiler: gcc
            compiler_version: default
            generator: ninja
            generator_type: singleconfig
            runner: ubuntu-24.04
          - os: linux
            os_version: ubuntu24.04
            architecture: x64
            architecture_variant: generic
            compiler: gcc
            compiler_version: default
            generator: ninjamulticonfig
            generator_type: multiconfig
            runner: ubuntu-24.04
          - os: linux
            os_version: ubuntu24.04
            architecture: x64
            architecture_variant: generic
            compiler: clang
            compiler_version: default
            generator: ninja
            generator_type: singleconfig
            runner: ubuntu-24.04
          - os: linux
            os_version: ubuntu24.04
            architecture: x64
            architecture_variant: generic
            compiler: clang
            compiler_version: default
            generator: ninjamulticonfig
            generator_type: multiconfig
            runner: ubuntu-24.04
          - os: windows
            os_version: v10
            architecture: x64
            architecture_variant: generic
            compiler: msvc
            compiler_version: default
            generator: msvc2022
            generator_type: multiconfig
            runner: windows-2022
          - os: windows
            os_version: v10
            architecture: x64
            architecture_variant: generic
            compiler: msvc
            compiler_version: default
            generator: msvc2026
            generator_type: multiconfig
            runner: windows-2025-vs2026
          - os: windows
            os_version: v10
            architecture: x64
            architecture_variant: generic
            compiler: msvcclang
            compiler_version: default
            generator: msvc2022
            generator_type: multiconfig
            runner: windows-2022
          - os: windows
            os_version: v10
            architecture: x64
            architecture_variant: generic
            compiler: msvcclang
            compiler_version: default
            generator: msvc2026
            generator_type: multiconfig
            runner: windows-2025-vs2026

    steps:
      - name: csCMake
        uses: actions/checkout@v6
        with:
          repository: cscosine/csCMake.git
          path: workspace/csCMake
          ref: orchestrator
          fetch-depth: 1
          token: ${{ secrets.ACTIONS_ORG_ACCESS }}

      - name: eigen3
        uses: actions/checkout@v6
        with:
          repository: cscosine/eigen3.git
          path: workspace/eigen3
          ref: orchestrator
          fetch-depth: 1
          token: ${{ secrets.ACTIONS_ORG_ACCESS }}

      - name: fmt
        uses: actions/checkout@v6
        with:
          repository: cscosine/fmt.git
          path: workspace/fmt
          ref: orchestrator
          fetch-depth: 1
          token: ${{ secrets.ACTIONS_ORG_ACCESS }}

      - name: fmt-eigen
        uses: actions/checkout@v6
        with:
          repository: cscosine/fmt-eigen.git
          path: workspace/fmt-eigen
          ref: orchestrator
          fetch-depth: 1
          token: ${{ secrets.ACTIONS_ORG_ACCESS }}

      - name: cpptrace
        uses: actions/checkout@v6
        with:
          repository: cscosine/cpptrace.git
          path: workspace/cpptrace
          ref: orchestrator
          fetch-depth: 1
          token: ${{ secrets.ACTIONS_ORG_ACCESS }}

      - name: magic_enum
        uses: actions/checkout@v6
        with:
          repository: cscosine/magic_enum.git
          path: workspace/magic_enum
          ref: orchestrator
          fetch-depth: 1
          token: ${{ secrets.ACTIONS_ORG_ACCESS }}

      - name: libassert
        uses: actions/checkout@v6
        with:
          repository: cscosine/libassert.git
          path: workspace/libassert
          ref: orchestrator
          fetch-depth: 1
          token: ${{ secrets.ACTIONS_ORG_ACCESS }}

      - name: tclap
        uses: actions/checkout@v6
        with:
          repository: cscosine/tclap.git
          path: workspace/tclap
          ref: orchestrator
          fetch-depth: 1
          token: ${{ secrets.ACTIONS_ORG_ACCESS }}

      - name: Catch2
        uses: actions/checkout@v6
        with:
          repository: cscosine/Catch2.git
          path: workspace/Catch2
          ref: orchestrator
          fetch-depth: 1
          token: ${{ secrets.ACTIONS_ORG_ACCESS }}

      - name: pipes
        uses: actions/checkout@v6
        with:
          repository: cscosine/pipes.git
          path: workspace/pipes
          ref: orchestrator
          fetch-depth: 1
          token: ${{ secrets.ACTIONS_ORG_ACCESS }}

      - name: NamedType
        uses: actions/checkout@v6
        with:
          repository: cscosine/NamedType.git
          path: workspace/NamedType
          ref: orchestrator
          fetch-depth: 1
          token: ${{ secrets.ACTIONS_ORG_ACCESS }}

      - name: tl-optional
        uses: actions/checkout@v6
        with:
          repository: cscosine/tl-optional.git
          path: workspace/tl-optional
          ref: orchestrator
          fetch-depth: 1
          token: ${{ secrets.ACTIONS_ORG_ACCESS }}

      - name: tl-expected
        uses: actions/checkout@v6
        with:
          repository: cscosine/tl-expected.git
          path: workspace/tl-expected 
          ref: orchestrator
          fetch-depth: 1
          token: ${{ secrets.ACTIONS_ORG_ACCESS }}

      - name: cmake workflow on eigen3 CMake Workflow - (singleconfig)
        if: matrix.generator_type == 'singleconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/eigen3

      - name: cmake workflow on eigen3 CMake Workflow - (multiconfig)
        if: matrix.generator_type == 'multiconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/eigen3

      - name: cmake workflow on fmt CMake Workflow - (singleconfig)
        if: matrix.generator_type == 'singleconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-debug
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/fmt

      - name: cmake workflow on fmt CMake Workflow - (multiconfig)
        if: matrix.generator_type == 'multiconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-debug-release
        working-directory: workspace/fmt

      - name: cmake workflow on fmt-eigen CMake Workflow - (singleconfig)
        if: matrix.generator_type == 'singleconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/fmt-eigen

      - name: cmake workflow on fmt-eigen CMake Workflow - (multiconfig)
        if: matrix.generator_type == 'multiconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/fmt-eigen

      - name: cmake workflow on cpptrace CMake Workflow - (singleconfig)
        if: matrix.generator_type == 'singleconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-debug
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/cpptrace

      - name: cmake workflow on cpptrace CMake Workflow - (multiconfig)
        if: matrix.generator_type == 'multiconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-debug-release
        working-directory: workspace/cpptrace

      - name: cmake workflow on magic_enum CMake Workflow - (singleconfig)
        if: matrix.generator_type == 'singleconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-debug
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/magic_enum

      - name: cmake workflow on magic_enum CMake Workflow - (multiconfig)
        if: matrix.generator_type == 'multiconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-debug-release
        working-directory: workspace/magic_enum

      - name: cmake workflow on libassert CMake Workflow - (singleconfig)
        if: matrix.generator_type == 'singleconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-debug
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/libassert

      - name: cmake workflow on libassert CMake Workflow - (multiconfig)
        if: matrix.generator_type == 'multiconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-debug-release
        working-directory: workspace/libassert

      - name: cmake workflow on tclap CMake Workflow - (singleconfig)
        if: matrix.generator_type == 'singleconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/tclap

      - name: cmake workflow on tclap CMake Workflow - (multiconfig)
        if: matrix.generator_type == 'multiconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/tclap

      - name: cmake workflow on Catch2 CMake Workflow - (singleconfig)
        if: matrix.generator_type == 'singleconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-debug
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/Catch2

      - name: cmake workflow on Catch2 CMake Workflow - (multiconfig)
        if: matrix.generator_type == 'multiconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-debug-release
        working-directory: workspace/Catch2

      - name: cmake workflow on pipes CMake Workflow - (singleconfig)
        if: matrix.generator_type == 'singleconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/pipes

      - name: cmake workflow on pipes CMake Workflow - (multiconfig)
        if: matrix.generator_type == 'multiconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/pipes

      - name: cmake workflow on NamedType CMake Workflow - (singleconfig)
        if: matrix.generator_type == 'singleconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/NamedType

      - name: cmake workflow on NamedType CMake Workflow - (multiconfig)
        if: matrix.generator_type == 'multiconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/NamedType

      - name: cmake workflow on tl-optional CMake Workflow - (singleconfig)
        if: matrix.generator_type == 'singleconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/tl-optional

      - name: cmake workflow on tl-optional CMake Workflow - (multiconfig)
        if: matrix.generator_type == 'multiconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/tl-optional

      - name: cmake workflow on tl-expected CMake Workflow - (singleconfig)
        if: matrix.generator_type == 'singleconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/tl-expected 

      - name: cmake workflow on tl-expected CMake Workflow - (multiconfig)
        if: matrix.generator_type == 'multiconfig'
        shell: bash
        run: |
          set -e
          cmake --workflow workflow-csv1-${{ matrix.os }}-${{ matrix.os_version }}-${{ matrix.architecture }}-${{ matrix.architecture_variant }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.generator }}-release
        working-directory: workspace/tl-expected 
